[package]
name = "daily_log"
version = "0.23.0"
publish = false
authors = { workspace = true }
edition = { workspace = true }
description = { workspace = true }
keywords = { workspace = true }
categories = { workspace = true }
repository = { workspace = true }
homepage = { workspace = true }
readme = { workspace = true }
license = { workspace = true }

[lints]
workspace = true

[dependencies]
chrono = { workspace = true }
config = { path = "../config" }
dates = { path = "../dates" }
highlight = { path = "../highlight" }
miette = { workspace = true }
thiserror = { workspace = true }
undo = { path = "../undo" }

[dev-dependencies]
tempfile = { workspace = true }
