[package]
name = "summary"
version = "0.24.0"
publish = false
authors = { workspace = true }
edition = { workspace = true }
description = { workspace = true }
keywords = { workspace = true }
categories = { workspace = true }
repository = { workspace = true }
homepage = { workspace = true }
readme = { workspace = true }
license = { workspace = true }

[lints]
workspace = true

[dependencies]
async-trait = { workspace = true }
chrono = { workspace = true }
config = { path = "../config" }
daily_log = { path = "../daily_log" }
dates = { path = "../dates" }
highlight = { path = "../highlight" }
miette = { workspace = true }
llm = { path = "../llm" }
thiserror = { workspace = true }
undo = { path = "../undo" }

[dev-dependencies]
tempfile = { workspace = true }
tokio = { workspace = true }
