[package]
name = "cli"
version = "0.24.0"
authors = { workspace = true }
edition = { workspace = true }
description = { workspace = true }
keywords = { workspace = true }
categories = { workspace = true }
repository = { workspace = true }
homepage = { workspace = true }
readme = { workspace = true }
license = { workspace = true }

[lints]
workspace = true

[[bin]]
name = "swelog"
path = "src/main.rs"

[dependencies]
base_url = { path = "../base_url" }
chrono = { workspace = true }
clap = { workspace = true, features = ["derive"] }
config = { path = "../config" }
credentials = { path = "../credentials" }
daily_log = { path = "../daily_log" }
dates = { path = "../dates" }
futures = { workspace = true }
github = { path = "../github" }
google_calendar = { path = "../google_calendar" }
highlight = { path = "../highlight" }
llm = { path = "../llm" }
linear = { path = "../linear" }
markdown = { path = "../markdown" }
miette = { workspace = true, features = ["fancy"] }
summary = { path = "../summary" }
thiserror = { workspace = true }
time = { path = "../time" }
tokio = { workspace = true }
undo = { path = "../undo" }
updates = { path = "../updates" }
url = { workspace = true }

[dev-dependencies]
assert_cmd = { workspace = true }
command-extra = { workspace = true }
httpmock = { workspace = true }
predicates = { workspace = true }
serde_json = { workspace = true }
tempfile = { workspace = true }
