[package]
name = "time"
version = "0.24.0"
publish = false
authors = { workspace = true }
edition = { workspace = true }
description = { workspace = true }
keywords = { workspace = true }
categories = { workspace = true }
repository = { workspace = true }
homepage = { workspace = true }
readme = { workspace = true }
license = { workspace = true }

[lints]
workspace = true

[dependencies]
chrono = { workspace = true }
