[package]
name = "llm"
version = "0.24.0"
publish = false
authors = { workspace = true }
edition = { workspace = true }
description = { workspace = true }
keywords = { workspace = true }
categories = { workspace = true }
repository = { workspace = true }
homepage = { workspace = true }
readme = { workspace = true }
license = { workspace = true }

[lints]
workspace = true

[dependencies]
async-trait = { workspace = true }
base_url = { path = "../base_url" }
chrono = { workspace = true }
config = { path = "../config" }
credentials = { path = "../credentials" }
dates = { path = "../dates" }
miette = { workspace = true }
ollama-rs = { workspace = true }
reqwest = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
thiserror = { workspace = true }
